const dogBreedData = {
  "Golden Retriever": { avgWeightKg: 29.5, avgLifespanYears: 13.2 },
  "Labrador Retriever": { avgWeightKg: 29.5, avgLifespanYears: 13.1 },
  "German Shepherd": { avgWeightKg: 31.8, avgLifespanYears: 11.3 },
  Bulldog: { avgWeightKg: 22.7, avgLifespanYears: 9.8 },
  Beagle: { avgWeightKg: 10.0, avgLifespanYears: 12.5 },
  Poodle: { avgWeightKg: 25.0, avgLifespanYears: 14.0 },
  Chihuahua: { avgWeightKg: 2.5, avgLifespanYears: 11.8 },
  "Yorkshire Terrier": { avgWeightKg: 3.0, avgLifespanYears: 13.3 },
  Boxer: { avgWeightKg: 29.5, avgLifespanYears: 11.3 },
  Dachshund: { avgWeightKg: 9.0, avgLifespanYears: 13.2 },
  "Shih Tzu": { avgWeightKg: 6.0, avgLifespanYears: 12.8 },
  Rottweiler: { avgWeightKg: 45.4, avgLifespanYears: 10.6 },
  "Doberman Pinscher": { avgWeightKg: 36.3, avgLifespanYears: 11.2 },
  "Great Dane": { avgWeightKg: 63.5, avgLifespanYears: 10.6 },
  "Siberian Husky": { avgWeightKg: 22.7, avgLifespanYears: 11.9 },
  "Cavalier King Charles Spaniel": { avgWeightKg: 6.8, avgLifespanYears: 11.8 },
  "Boston Terrier": { avgWeightKg: 9.0, avgLifespanYears: 11.8 },
  "Australian Shepherd": { avgWeightKg: 22.7, avgLifespanYears: 13.7 },
  Pomeranian: { avgWeightKg: 2.5, avgLifespanYears: 12.2 },
  Maltese: { avgWeightKg: 3.5, avgLifespanYears: 13.1 },
  "Bichon Frise": { avgWeightKg: 7.5, avgLifespanYears: 12.5 },
  "Border Collie": { avgWeightKg: 20.0, avgLifespanYears: 13.1 },
  "Bernese Mountain Dog": { avgWeightKg: 45.4, avgLifespanYears: 10.1 },
  "French Bulldog": { avgWeightKg: 11.3, avgLifespanYears: 9.8 },
  Pug: { avgWeightKg: 7.5, avgLifespanYears: 11.6 },
  "Cocker Spaniel": { avgWeightKg: 13.6, avgLifespanYears: 13.3 },
  "Miniature Schnauzer": { avgWeightKg: 8.2, avgLifespanYears: 13.3 },
  "English Springer Spaniel": { avgWeightKg: 20.4, avgLifespanYears: 13.5 },
  Newfoundland: { avgWeightKg: 54.4, avgLifespanYears: 11.0 },
  "Saint Bernard": { avgWeightKg: 63.5, avgLifespanYears: 9.3 },
  Bullmastiff: { avgWeightKg: 54.4, avgLifespanYears: 10.2 },
  Akita: { avgWeightKg: 45.4, avgLifespanYears: 11.4 },
  "Chow Chow": { avgWeightKg: 29.5, avgLifespanYears: 12.1 },
  Samoyed: { avgWeightKg: 27.2, avgLifespanYears: 13.1 },
  "Great Pyrenees": { avgWeightKg: 45.4, avgLifespanYears: 10.9 },
  "Irish Wolfhound": { avgWeightKg: 54.4, avgLifespanYears: 9.9 },
  Leonberger: { avgWeightKg: 54.4, avgLifespanYears: 10.0 },
  Mastiff: { avgWeightKg: 68.0, avgLifespanYears: 9.0 },
  "Cane Corso": { avgWeightKg: 45.4, avgLifespanYears: 8.1 },
  "Presa Canario": { avgWeightKg: 45.4, avgLifespanYears: 7.7 },
  "Caucasian Shepherd Dog": { avgWeightKg: 45.4, avgLifespanYears: 5.4 },
};

export default dogBreedData;
